### ISSUE TITLE
clang dockers contain gcc compiler

### ISSUE THREAD

**Issue by madebr** [conan-io/conan-docker-tools#108]
The clang dockers still contain a gcc toolchain, which may lead to wrong/unexpected packages.

Example issue: https://github.com/bincrafters/community/issues/669

Is it possible to remove the gcc toolchain from them?

**Comment by uilianries** [comment]
no, it's not possible. The clang package (apt) requires g++-multilib that requires gcc. Some libraries and headers are shared between both packages. We can't remove only gcc because some important components will be removed together. 

Maybe we could remove gcc manually, like `rm /usr/bin/gcc` and all related stuff, but it could result in broken packages. Probably this will break SystemPackageTool when installing on system_requirements

**Comment by madebr** [comment]
Thanks for investigating.
What might be useful is replacing gcc and g++ with a wrapper script that sets some variable or writes to some file when executed.
That way, conan can detect whether gcc was executed.

**Comment by uilianries** [comment]
What kind of wrapper? which variables? I have no idea how to implement this. Also, I don't know which side effects it could result when uninstalling or upgrading a package.

**Comment by madebr** [comment]
I propose something like the following:
Create a `gcc` and `g++` file containing the following content:
```
#!/usr/bin/env bash
>&2 echo "WARNING: g++ called on a clang docker image"

# Simple gcc detection
echo "1">"$HOME/GCC_DETECTED"

/usr/bin/gcc $@
```
`chmod a+x` both files and prepend the directory containing both files to the `PATH` environment variable.
Launch of `gcc` can be detected if `$HOME/GCC_DETECTED` exists (or if the warning is printed to the stderr).

This is not a perfect solution since scripts using `/usr/bin/gcc` will not be detected.
But I think those can be ignored.
