### ISSUE TITLE
Upgrade Python version to 3.8 or 3.9

### ISSUE THREAD

**Issue by jgsogo** [conan-io/conan-docker-tools#259]
### Description of Problem, Request, or Question

Needed for pytorch: https://github.com/conan-io/conan-center-index/pull/5100

### Environment Details
* Conan Docker Tools image: **all**
* Operating System: **Linux**
* Operation System Version: **Ubuntu 16.04**
* Python version (If you are building some image): **python 3.7.0** 😄

**Comment by Croydon** [comment]
This is contradicting with the motivation for using an older Python version on purpose in order to prevent that people use the newest Python features which then won't work for all Python versions supported by Conan. (see also https://github.com/conan-io/conan-docker-tools/pull/153)

I think having a Python recipe is probably the way to go if a project requires a specific version of Python (https://github.com/conan-io/conan-center-index/pull/1510)

**Comment by jgsogo** [comment]
You are absolutely right, @Croydon.
