### ISSUE TITLE
[suggestion] Update CMake version to 3.21.1 or newer

### ISSUE THREAD

**Issue by BrentH04** [conan-io/conan-docker-tools#298]
### Description of Problem, Request, or Question
CMake/ctest version 3.21.1  introduces the capability to output a test report in the same XML format
produced by JUnit and other testing frameworks. This XML format is widely supported by various 
visualization and exploitation tools, and can be injested natively by both GitLab CI/CD and Jenkins
pipelines to show test results associated with a build or merge requests. Previous versions of 
cmake/ctest did NOT provide the capability of producing reports in this XML file format and so more
complicated pipeline steps are required to integrate into Gitlab, Jenkins, or other tools. 

### Environment Details
* Conan Docker Tools image: **conanio/gcc10:1.38.0**
* Operating System: **Linux**
* Operation System Version: **Kubernetes 1.19.7, Docker CE 19.3.14 on RHEL 7.9**
* Python version (If you are building some image): **N/A**

### Steps to reproduce (Include if Applicable)
After installing the 3.21.1 version of CMake into the Conan container using PIP the following command generates a GitLab/Jenkins compatible unit test report when using the `conanio/gcc10` container to build a C++ project: 
`ctest -j1 --output-junit ../${UNITTEST_REPORT_FILE}`

**Comment by uilianries** [comment]
We will keep aligned with the [Tribe](https://github.com/conan-io/tribe/blob/main/design/004-tools-cmake.md), which is CMake 3.15, so we can guarantee a minimal Conan behavior.

For newer versions, I recommend you using [CMake](https://conan.io/center/cmake) conan package as build requirement instead.

**Comment by chausner** [comment]
+1 for updating CMake in the Docker images more often to the latest version. 

@uilianries Here is a concrete example that I have run into: package `cryptopp` requires CMake 3.20 or later. Since the CMake version in CI is older, the recipe is forced to specify `cmake/3.24` as build requirement. This works fine for the common platforms but leads to problems when attempting to use the recipe on platforms where CMake cannot be built from source. This is unfortunate because even if the build machine has a recent-enough CMake version already installed system-wide, Conan will still attempt to build the CMake build requirement from source and fails. So effectively, the recipe cannot be used on these platforms just due to the build requirement.

**Comment by Croydon** [comment]
@chausner Could you please open a new issue in the Conan Center Index repository for which platform and configuration the CMake recipe fails to build? That is interesting to hear

**Comment by chausner** [comment]
> @chausner Could you please open a new issue in the Conan Center Index repository for which platform and configuration the CMake recipe fails to build? That is interesting to hear

It can be reproduced with the `conanio/android-clang8` Docker image. However, I think the actual problem is that the image does not come with compilers for the build operating system, and for some reason, Conan tries to compile CMake build requirement using the Android NDK [which fails](https://gitlab.kitware.com/cmake/cmake/-/issues/21399).

I got it working by creating and specifying appropriate build and host profiles. Conan then used pre-compiled packages for CMake from ConanCenter.

**Comment by uilianries** [comment]
@chausner Please, open a new issue explaining your case. Also

- android and arm docker image are no longer maintained
- **ALWAYS** use two profiles when cross-building
