### ISSUE TITLE
 groupadd 1000 -g 1000 work on ubuntu16.04 and not in 20.04

### ISSUE THREAD

**Issue by Tudyx** [conan-io/conan-docker-tools#322]
I try to build modern image on ubuntu 20.04 by changing the `DISTRO` and `DISTRO_VERSION` variables in the `.env` file.
Unfortunatly the command ` groupadd 1000 -g 1000` seems to work in **ubuntu16.04** but nor for **20.04** version. I know that it's planned to only use  **ubuntu16.04**  for modern image but maybe it will be a problem in the future.

The eror message on **ubuntu20.04** :
```sh
groupadd: '1000' is not a valid group name
```

**Comment by uilianries** [comment]
Could you give more details? Command line, version used, log, etc ... ?

**Comment by Tudyx** [comment]
I updated the description ;)

**Comment by uilianries** [comment]
@Tudyx it occurs because `groupadd` version. IIRC accepting group names as numbers only is considered a bug. We would need to update the group name to something equal or very similar to default group names in Ubuntu. I remember I had similar problem when creating Docker images for Conan. Indeed we should think about it, because probably Ubuntu will no longer use 1000 as group name due that command.
