### ISSUE TITLE
[question] CMake version in `modern` docker images

### ISSUE THREAD

**Issue by planetmarshall** [conan-io/conan-docker-tools#329]
I note that the CMake version in the modern docker images has been set to 3.15.7 to match the version in CCI.

I just wondered is there any particular reason to *not* use the latest CMake? I only ask as I was using the modern images in CI and starting getting some build failures when updating to the latest images.

Obviously I can build my own images with the latest CMake but I'd rather use the ones in conanio because I'm lazy...:)

(In all seriousness - thanks for providing these images)

**Comment by uilianries** [comment]
@planetmarshall the reason is because all new Docker images are modeled according the expected versions for Conan 2.0 which were aligned and voted by the tribe.

For instance, the CMake minimal version voted was 3.15: https://github.com/conan-io/tribe/blob/main/design/004-tools-cmake.md

And Python is 3.6: https://github.com/conan-io/tribe/blob/main/design/003-codebase-python.md

We must keep those versions to ensure total compatibility. However, if you want a different CMake version installed, you could use a different entrypoint, for example:

`install_cmake.sh`
```bash
#!/bin/bash
pip install -U cmake
/bin/bash
```

    docker run --rm -ti -v ${PWD}:/tmp/project --entrypoint /tmp/project/install_cmake.sh  conanio/gcc11-ubuntu16.04 /bin/bash
