### ISSUE TITLE
[?] Install conan-center hook by default on Modern images

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#334]
### Description of Problem, Request, or Question

As all modern images are designed for Conan Center Index, and we need to check Conan Center hook before merging, installing it by default would help to prevent hooks errors before opening the PR.

**Comment by Croydon** [comment]
If you go ahead with this, please give the option to opt-out of it. Some hooks are good -if- you want to fulfill certain community standards, but there are also some hooks that make no sense outside of CCI. Like setting the `homepage` attribute to CCI.

The containers might be for CCI, but there is no reason to make it artificial harder to use them outside

**Comment by uilianries** [comment]
Yes, I agree. Also, we release one new image version per month, but hooks can be updated every week. I'm considering running an entrypoint when starting a new container, instead of installing the hook.

Or, we can install conan-center hook, but keep it disabled by default.

**Comment by jgsogo** [comment]
At this moment we are building two sets of images, ones like `conanio/gcc10-ubuntu16` and others like `conanio/gcc10-ubuntu16-jenkins`, we are using the `-jenkins` ones in C3i, and we can assume these ones are specific for C3i usage. These images would be the ones to consider.

Pre-installing the hooks will save a lot of bandwith/time (needs benchmarking) because we are installing them so many times for every build in C3i (at least, once per configuration). The only drawback is, as said, _"hooks can be updated every week"_.

If we preinstall hooks, we would need to regenerate docker images every time hooks are modified (and we want to start using that modification in c3i), now the _deployment_ is automatic.

**Comment by jgsogo** [comment]
Also, changes to hooks don't need to be deployed right away. The same happens with changes merged to `master` in this repository, they are not automatically available in CCI.

We deploy at least once a month (with every Conan release) and we can deploy manually if needed. Maybe we can trigger the **deployment process every week** and that would be enough, no need to connect `hooks` repository to this CI.

**Comment by uilianries** [comment]
> Maybe we can trigger the deployment process every week and that would be enough, no need to connect hooks repository to this CI.

That's a good option too. We can store the conan-center hook checksum and avoid extra builds when not needed.

**Comment by SSE4** [comment]
we might put that on hold for now. hooks aren't compatible with v2, and we don't know if they will be, or will we replace hooks by some pylint plug-ins.

**Comment by uilianries** [comment]
> we might put that on hold for now. hooks aren't compatible with v2, and we don't know if they will be, or will we replace hooks by some pylint plug-ins.

Excellent point. Indeed we need to consider Conan V2.
