### ISSUE TITLE
Do not build all patch versions

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#408]
### Description of Problem, Request, or Question

Right now, we are building the last 3 minor versions. Which include all patch versions.

For instance:

1.45.0, 1.46.0, 1.46.1, 1.46.2, 1.47.0

We are running 1.45.0 on Conan Center, and the next version will be 1.46.2.

The versions 1.46.0 and 1.46.1 are not used and consume +30min to be built on CI.

**Comment by jgsogo** [comment]
We build all the versions starting with the one used in CCI and we need to keep doing the same. Generating all the patch versions decouples this project from CCI (and ConanCenter production) because we don't need to worry about images that might not have been generated. And this logic is executed for the CI that generates the images that are used for CCI. 

Regular CI only builds the Conan version that is hardcoded in this repository (which should be the latest one).

**Comment by jgsogo** [comment]
Now that we upgrade Conan version in CCI, only the versions equal-or-greater than that are being generated:

![image](https://user-images.githubusercontent.com/1406456/166636336-cff3e960-fbca-4020-97dd-f51c504c6960.png)

**Comment by uilianries** [comment]
Great, much better!
