### ISSUE TITLE
Create build image, using only conan-based build tools

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-docker-tools#473]
### Description of Problem, Request, or Question
It would be nice to use build tools, produced with conan to compile conan recipes. To implement this concept, I have created this project:
https://github.com/AndreyMlashkin/minimalistic_conan_docker
Note: this docker file is optimized not for industrial use, but for faster development.

### Environment Details
* Conan Docker Tools image: **Ubuntu latest**
* Operating System: **Linux**

### Steps to reproduce (Include if Applicable)
git clone git@github.com:AndreyMlashkin/minimalistic_conan_docker.git
cd minimalistic_conan_docker
docker build .

### Build logs (Include if Available)

```
Downloading conan_sources.tgz
zlib/1.2.11: Configuring sources in /root/.conan/data/zlib/1.2.11/_/_/source/src
zlib/1.2.11: 
zlib/1.2.11: Copying sources to build folder
zlib/1.2.11: Building your package in /root/.conan/data/zlib/1.2.11/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646
zlib/1.2.11: Generator txt created conanbuildinfo.txt
zlib/1.2.11: Calling generate()
zlib/1.2.11: Preset 'release' added to CMakePresets.json. Invoke it manually using 'cmake --preset release'
zlib/1.2.11: If your CMake version is not compatible with CMakePresets (<3.19) call cmake like: 'cmake <path> -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/root/.conan/data/zlib/1.2.11/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646/build/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release'
zlib/1.2.11: Aggregating env generators
zlib/1.2.11: Calling build()
zlib/1.2.11: CMake command: cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/root/.conan/data/zlib/1.2.11/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/zlib/1.2.11/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan/data/zlib/1.2.11/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646/src"
-- Using Conan toolchain: /root/.conan/data/zlib/1.2.11/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646/build/generators/conan_toolchain.cmake
-- Conan toolchain: Setting CMAKE_POSITION_INDEPENDENT_CODE=ON (options.fPIC)
-- Conan toolchain: Setting BUILD_SHARED_LIBS = OFF
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/root/.conan/data/zlib/1.2.11/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646/build/Release/CMakeFiles/CMakeOutput.log".
zlib/1.2.11: ERROR: Package 'dfbe50feef7f3c6223a476cd5aeadb687084a646' build failed
zlib/1.2.11: WARN: Build folder /root/.conan/data/zlib/1.2.11/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646/build/Release
zlib/1.2.11: 
ERROR: zlib/1.2.11: Error in build() method, line 88
	cmake.configure()
	ConanException: Error 1 while executing cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="/root/.conan/data/zlib/1.2.11/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646/build/generators/conan_toolchain.cmake" -DCMAKE_INSTALL_PREFIX="/root/.conan/data/zlib/1.2.11/_/_/package/dfbe50feef7f3c6223a476cd5aeadb687084a646" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_BUILD_TYPE="Release" "/root/.conan/data/zlib/1.2.11/_/_/build/dfbe50feef7f3c6223a476cd5aeadb687084a646/src"
The command '/bin/sh -c ls -l -a && chmod +x activate.sh && . ./activate.sh && conan install zlib/1.2.12@ --build zlib -pr:b=default -pr:h=host_profile --build missing' returned a non-zero code: 1
```
Full build log does not fit to the console buffer, so there is a cut version:
[build_log.txt](https://github.com/conan-io/conan-docker-tools/files/9798414/build_log.txt)

**Comment by AndreyMlashkin** [comment]
@prince-chrismc @microblink @Roalter @Croydon @KerstinKeller @akleber - if you remember, we have discussed this on the last day of conan conference

Also ping
@uilianries @SSE4 

I think, it's an interesting puzzle to solve for all of us :)

**Comment by uilianries** [comment]
We have discussed it in the past, indeed the idea is using Conan packages instead of some system libraries. For tools I don't think it will be possible for all cases, because chicken-egg problem, GCC is one of those cases.

**Comment by AndreyMlashkin** [comment]
Here is the list of the build tools and it can be expanded for a concrete project needs
https://github.com/AndreyMlashkin/minimalistic_conan_docker/blob/main/requirements.txt

**Comment by uilianries** [comment]
>  Step 2: install conan build tools

And who built Conan tools?

**Comment by AndreyMlashkin** [comment]
> > Step 2: install conan build tools
> 
> And who built Conan tools?

Local client, using tools from Step 1.

**Comment by AndreyMlashkin** [comment]
Here is step 2 in my Dockerfile
https://github.com/AndreyMlashkin/minimalistic_conan_docker/blob/a09c08b9a9df8d91a47f47f95ae50dbade82f634/Dockerfile#L19

**Comment by AndreyMlashkin** [comment]
> And who built that package listed there?

Tools, installed with apt-get install from step 1
https://github.com/AndreyMlashkin/minimalistic_conan_docker/blob/a09c08b9a9df8d91a47f47f95ae50dbade82f634/Dockerfile#L12

**Comment by uilianries** [comment]
@AndreyMlashkin We no longer use gcc from apt get, because we can't managed APT repository, that's why we build from sources.

**Comment by AndreyMlashkin** [comment]
This whole repository is a proof of concept. It needs a lot of polishing to become an industrial solution.
On this point, it does not matter, from where gcc comes, if it comes not from conan.
This proof of concept already shows a problem with conan-client or with conan recipes.
@uilianries, have you tried to build this docker?

**Comment by AndreyMlashkin** [comment]
The actual usecase for me is this:
https://github.com/mmozeiko/docker-mingw-w64

I want to cross-compile from Linux to Windows using mingw-64, using conan.

**Comment by uilianries** [comment]
>  @uilianries, have you tried to build this docker?

I didn't build, but I read the Dockerfile.

> I want to cross-compile from Linux to Windows using mingw-64, using conan.

The problem is, those images are **focused** for Conan Center Index, not for industrial usage, neither for all the community, that's why we deprecated many images months ago. Including most of them which are required by the community, and we accept, but become outdated and abandoned.

Also, using APT was a pain for us, not able to manage which package is installed. APT repo only make one version available and as soon as it's replaced, you can't install it again without workarounds. It was a strong motivation for using compilers from sources, so we could configure what we want, without interfering in CCI.

Still, you can fork, customize and publish your Docker images. Thank you for bringing your propose but replacing building tools in CDT is not something which I'm inclined to risk now for a simple reason: It's working and any change could break the entire Conan Center.

**Comment by AndreyMlashkin** [comment]
Disregarding of usage, this docker shows a concrete problem and I am asking community for a help to deal with it.

For me, it's an elegant solution for chicken-egg problem and for me it was fun to try solving it and I want to share this puzzle with the others.

**Comment by samuel-emrys** [comment]
> And who built that package listed there? You see, it does not solve chicken-egg problem, you always need some base platform to built the first Conan package.
> 
> Using GCC package as example, you will need a GCC conan package to build another GCC conan package, but the first GCC package can not be assured as available, because we have the scenario where we create a new image and the compiler is highly attached to the system libs.
> 
> Adding Conan packages to replace system packages, like zlib, or build tools like cmake, there is no big deal, but very basic tools like the compiler, it will not work for us. Also, you have to consider the scenario when creating a new image flavor, where there is no package available yet for that Docker image and we need to download a package which was built another image (based on the profile only) and validate very well if it's compatible and will not break users.

The obvious solution to this is to use some kind of bootstrapping mechanism. Installing gcc from `apt` is one way to achieve this, but another would be to make an exception in C3i to have binary packages for the most fundamental building blocks. In the case of a compiler, you would only need binaries for one version of configurations from which to bootstrap, and from there you could build up the rest of the tree from source.

I'm not sure what the dependency tree might look like for gcc 12.2.0, but lets assume it looks like the following:

12.2.0 <- 10.0.0 <- 7.0.0 <- 4.3.0 <- 2.1.0

Now, @uilianries you quite rightly point out that there's a chicken and egg problem here - but if you make the commitment to provide binaries for an old version, say 2.1.0, then this can be used to bootstrap the rest of the compilers for each architecture, and you would have all of this self-contained within a repository that you manage - no more relying on the `apt` repositories to bootstrap for you (or not addressing this at all). This is essentially how compilers have naturally evolved - bootstrapping, so I think that this is rather a natural solution to this problem, since it is not unique to package management but a property of the problem itself.

I'm sure that this has been considered before - is there a reason that this isn't acceptable on C3i? This would make managing CI environments substantially easier, IMO. I really hope this goal is something that the JFrog team don't give up on because it would be an enormous benefit to be able to build our entire dependency tree from source (bootstrapping notwithstanding).

Also - I realise that this isn't relevant to `conan-docker-tools` specifically, but I figured that this is where some recent discussion on the topic _is_ happening. If you'd like me to crosspost elsewhere happy to do so.
