### ISSUE TITLE
Have conan modern 

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [conan-io/conan-docker-tools#491]
Hi conan community,

I see in https://github.com/conan-io/conan-docker-tools/tree/master/modern#ubuntu-1804-bionic-as-default-distro-october-2022 that ubuntu-1804 is now supported and old ubuntu-1604 based Docker images are deprecated.
But only these old ones are automatically updated according to latest conan release.
Could it be possible to have also ubuntu-1804 based images automatically updated?

Regards.

**Comment by RubenRBS** [comment]
Thanks for the heads-up, we'll look into it :)

**Comment by uilianries** [comment]
Closing this issue, because we actually could not use Ubuntu 18.04 because there was a mess with glibc and libstdc++ versions, causing breakage and errors when building packages with different versions.

In the future, when supporting only Conan 2.x, we will be moving to something newer like 20.04 or 22.04.
