### ISSUE TITLE
Any hope of some Windows examples?

### ISSUE THREAD

**Issue by ShamanTcler** [conan-io/conan-docker-tools#50]
Title pretty much says it all

**Comment by lasote** [comment]
I haven't tried windows containers at all... I only know that @solvingJ has been using windows containers. What do you need exactly?

**Comment by solvingj** [comment]
@lasote do you want to try supporting this under this project? 

https://github.com/bincrafters/docker-win1803-vctools1572/blob/master/Dockerfile

**Comment by lasote** [comment]
oh! Definitely, We would need some time to play with it but would be a great addition.

**Comment by solvingj** [comment]
Sounds good. let me know if you want me to do anything to get it included.

**Comment by lasote** [comment]
@danimtb @jgsogo @memsharded Anyone would like to experiment a little with Docker windows containers?

**Comment by ShamanTcler** [comment]
I will soon as I get over this cold. Does this mean you have something to try, or you want me to build it?

If you want me to build it may take a while.

**Comment by solvingj** [comment]
Excellent, thanks for sharing.  FYI, we switched from `choco install svn` to `choco install tortoisesvn` because the version of SVN that comes with the former is surprisingly old (1.8.7 i think), and we needed the features in 1.9.0+. 

Can I ask what the reason was for using powershell to install GIT that way?

**Comment by db4** [comment]
> Can I ask what the reason was for using powershell to install GIT that way?

Due to that problem: https://github.com/git-for-windows/git/issues/1007
Chocolatey Git was(?) affected, busybox one seemed to work.

**Comment by uilianries** [comment]
@lasote I have two important questions:

- Which name we should use for Windows images? 
  Suggestions:
  - conanmsvc12, conanmsvc14, conanmsvc15
  - conanvisual12, conanvisual14, conanvisual15
  - conanvisualstudio2015-14, conanvisualstudio2017-15

- Windows images are **HUGE**, >10GB each! I can't upload using appveyor because during the section I receive the follow error:
> Build exceeded allowed resource quotas. Fix your build to consume less resources or contact AppVeyor support to request quotas increase.

We could use Appveyor to build and validate only.

We need to provide some way to upload each docker image. Could we use JFrog infrastructure + Jenkins? Upload 10GB is not for amateur workspace.

**Comment by solvingj** [comment]
i guess we should open ticket with Appveyor team.  If there's no way to make a Windows container with vs_buildtools that's less than 10 GB, then that is a fundamental issue likely to block a lot of other use cases.  Maybe they don't realize.

**Comment by uilianries** [comment]
I'm trying on Azure now, it's working :smile_cat:

**Comment by Croydon** [comment]
Is this 10GB traffic limitation on AppVeyor only for uploads or also downloads? Meaning, can we use the container images on AppVeyor as long as we are building them somewhere else?

**Comment by uilianries** [comment]
@Croydon I agree with ` conanmsvc12` but we need to respect CPT vars, `CONAN_VISUAL_VERSIONS`. Sounds weird because the env var uses VISUAL but docker image uses msvc.

About Appveyor I don't know about the limitation. I sent an email asking about. I'll copy the answer here.

**Comment by uilianries** [comment]
>  From: Appveyor (Support staff)
> You were exceeding VM disk size quota of 90GB and also outgoing network traffic quota of 2GB.
> I increased the VM disk size quota to 100GB which should be enough for you to run your build.

**Comment by Croydon** [comment]
> I agree with conanmsvc12 but we need to respect CPT vars, CONAN_VISUAL_VERSIONS. 

I would rather map them internally from the CONAN_VISUAL_VERSIONS variable to the docker names instead of continuing a rather bad naming schema for new containers 🤔
