### ISSUE TITLE
Where are conan2 actual docker images?

### ISSUE THREAD

**Issue by AndreyMlashkin** [conan-io/conan-docker-tools#580]
Question: where are the actual conan2 docker images, is there any documentation about them?

From the current documentation page:
![image](https://github.com/conan-io/conan-docker-tools/assets/3842441/c4c547cf-cc1a-485f-8ec3-cf0ad242f34b)

I have tried to pull gcc13:

```
$ docker pull conanio/gcc13-ubuntu18.04
Using default tag: latest
Error response from daemon: pull access denied for conanio/gcc13-ubuntu18.04, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Then I run a previous version:
```
$ docker run -it conanio/gcc12-ubuntu18.04
conan@b218529b807a:~$ conan -v
Conan version 1.54.0
```

Looks like a good old conan1.
Please, update the documentation:
- publish gcc13 image for conan1
- add conan2 docker images

**Comment by uilianries** [comment]
@AndreyMlashkin All tags available can be found in https://hub.docker.com/u/conanio directly.

For instance, `conanio/gcc11-ubuntu16.04`: 

https://hub.docker.com/r/conanio/gcc11-ubuntu16.04/tags

![Screenshot 2024-04-17 at 11-38-07 conanio_gcc11-ubuntu16 04 Tags Docker Hub](https://github.com/conan-io/conan-docker-tools/assets/4870173/10ac8380-ad3e-4acf-8e20-1e7ef1eebdae)

You can see both tags `1.64.0` and `2.2.2`, which means you can use the image based on the tag version as the same Conan client version. Using the tag version is the best way to keep the predictable behavior.

`docker pull conanio/gcc11-ubuntu16.04:2.2.2`

For now, are no longer generating the tag `latest` because it would require extra steps to check Conan versions and will affect the CI flow.

I'll update the documentation, clarifying about it.

**Comment by uilianries** [comment]
About the specific GCC13 image: It's deprecated, because is not used in ConanCenterIndex CI.

Please, check what images are still supported: https://github.com/conan-io/conan-docker-tools/tree/master/modern#gcc

These images were made for ConanCenterIndex CI, as reported here: https://github.com/conan-io/conan-docker-tools/blob/master/README.md

However, you still can download the Docker files and build locally.

**Comment by AndreyMlashkin** [comment]
> docker pull conanio/gcc11-ubuntu16.04:2.2.2
```
$ docker pull conanio/clang13-ubuntu18.04
Using default tag: latest
latest: Pulling from conanio/clang13-ubuntu18.04
Digest: sha256:9504b1097971e6ad0698b0a2b8e6c2090bc3ead8ae2b51d7e9b1922933468a30
Status: Image is up to date for conanio/clang13-ubuntu18.04:latest
docker.io/conanio/clang13-ubuntu18.04:latest
```

```
andrei@andrei-NKx0Sx:~/nil/zkllvm-assigner$ docker pull conanio/clang13-ubuntu18.04:2.2.2
Error response from daemon: manifest for conanio/clang13-ubuntu18.04:2.2.2 not found: manifest unknown: manifest unknown
```

Why CI generates tags so selectively? And there is still 'latest' tag....

**Comment by uilianries** [comment]
> docker pull conanio/clang13-ubuntu18.04

Like I commented before, you have to read the documentation to check what's maintained. This version is not maintained anymore. 

https://github.com/conan-io/conan-docker-tools/tree/master/modern#official-docker-images

Old images are not removed from hub.docker.

> Why CI generates tags so selectively? And there is still 'latest' tag....

It's not selective, it's a best practice recommend by Docker project:

https://docs.docker.com/develop/dev-best-practices/

> When building images, always tag them with useful tags which codify version information, intended destination (prod or test, for instance), stability, or other information that's useful when deploying the application in different environments. Don't rely on the automatically-created latest tag.
