### ISSUE TITLE
Could not inflate tar.xz

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-docker-tools#68]
After to update our images with python3 only, @ericLemanissier reported some error involving tar.xz file when building conan-qt package.

Seems pyenv didn't install lzma support.

Logs:
https://dev.azure.com/bincrafters/packages/_build/results?buildId=30&view=logs
https://travis-ci.org/bincrafters/conan-qt/jobs/448257590#L1328

**Comment by ericLemanissier** [comment]
the current workaround I found is https://github.com/bincrafters/conan-qt/commit/7cd2708ba6ce7e6d9c4f09acd9abc544268b4caa : trying to import lzma, and if it fails, fall back to system call instead of tools.get. `import lzma` throws ModuleNotFoundError as can ben seen https://dev.azure.com/bincrafters/packages/_build/results?buildId=32&view=logs

**Comment by uilianries** [comment]
looks like I forgot to install some requirements before to build python using pyenv:

https://github.com/pyenv/pyenv/wiki/common-build-problems#requirements

I'm going to update to check the result.

**Comment by ericLemanissier** [comment]
yep, it works without workaround now. Thanks !
