### ISSUE TITLE
Using GCC7 conan is unable to find a compiler

### ISSUE THREAD

**Issue by Fohlen** [conan-io/conan-docker-tools#95]
See, e.g https://travis-ci.org/inexorgame/entity-system/jobs/480331511#L487

**Comment by Fohlen** [comment]
The same is true for me for `GCC8`

**Comment by uilianries** [comment]
Usually we user Conan Package Tools + Conan Docker Tools to build our packages. But in your case, you are running Conan directly in the container. I'll investigate further.

**Comment by uilianries** [comment]
The problem is because CMake sets `CXX=/usr/bin/c++`, but Conan only detects the correct compiler when it is named as `gcc`: https://github.com/conan-io/conan/blob/ecbb985897633f90f532fee23685e835f9b27add/conans/client/conf/detect.py#L94

Now we have two options, force CXX and CC in docker images or try to discover the correct compiler by conan default profile. I'll open an issue to Conan team and discuss the second option.

**Comment by Fohlen** [comment]
Imho forcing `/usr/bin/cxx` and `/usr/bin/cc` is the absolute standard approach of setting up the compiler on a `*nix` system

**Comment by uilianries** [comment]
I gonna open a PR here to fix this ASAP. The second option could take more time to be developed.
